version: 2.1

parameters:
  slack-mentions:
    type: string
    default: 'S01JP5A3ACQ'
  only_for_branches:
    type: string
    default: 'main'

orbs:
  slack: circleci/slack@3.4.2
  jq: circleci/jq@2.1.0

executors:
  go-executor:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/lacework/terraform-provider-lacework
  alpine:
    docker:
      - image: cibuilds/base:latest
    resource_class: small

jobs:
  unit-test:
    executor: go-executor
    steps:
      - checkout
      - run: make prepare
      - run: make test
      - run: make fmtcheck
      - slack/status:
          fail_only: true
          mentions: << pipeline.parameters.slack-mentions >>
          only_for_branches: <<pipeline.parameters.only_for_branches>>
  build:
    executor: go-executor
    steps:
      - checkout
      - run: make prepare
      - run: make build-cross-platform
      - persist_to_workspace:
          root: bin
          paths:
            - terraform-provider-lacework_*
      - slack/status:
          fail_only: true
          mentions: << pipeline.parameters.slack-mentions >>
          only_for_branches: <<pipeline.parameters.only_for_branches>>
  integration-test-linux:
    executor: go-executor
    steps:
      - checkout
      - attach_workspace:
          at: bin
      - run: make integration-test
      - slack/status:
          fail_only: true
          mentions: << pipeline.parameters.slack-mentions >>
          only_for_branches: <<pipeline.parameters.only_for_branches>>
  verify-release:
    executor: alpine
    steps:
      - checkout
      - run: scripts/release.sh verify
  trigger-release:
    executor: alpine
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c4:de:d2:af:7c:fd:39:0e:10:b3:37:d8:ff:5c:c5:b6"
      - run: scripts/release.sh trigger
  release:
    executor: go-executor
    steps:
      - checkout
      - jq/install
      - slack/notify:
          mentions: << pipeline.parameters.slack-mentions >>
          message: Releasing a new version of the terraform-provider-lacework repository
      - run: make prepare
      - run: echo "$GPG_SECRET_KEY" | base64 --decode | gpg --import --no-tty --batch --yes
      - run: scripts/release.sh publish
      - slack/status:
          mentions: << pipeline.parameters.slack-mentions >>

workflows:
  version: 2
  build_test_trigger-release:
    jobs:
      - unit-test
      - build
      - integration-test-linux:
          requires:
            - build
      - trigger-release:
          requires:
            - unit-test
            - integration-test-linux
          filters:
            branches:
              only: main

  verify-release:
    jobs:
      - verify-release:
          filters:
             branches:
               only: release

  release-from-tag:
    jobs:
      - release:
          filters:
            tags:
               only: /^v.*/
            branches:
              ignore: /.*/
          context: techally_releases

  nightly:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only: main
    jobs:
      - unit-test
      - build
      - integration-test-linux:
          requires:
            - build

