terraform {
  required_providers {
    lacework = {
      source = "lacework/lacework"
    }
  }
}

resource "lacework_alert_channel_service_now" "example" {
  name                 = var.channel_name
  instance_url         = var.instance_url
  username             = var.username
  password             = var.password
  custom_template_file = var.custom_template_file
  // test_integration input is used in this example only for testing
  // purposes, it help us avoid sending a "test" request to the
  // system we are integrating to. In production, this should remain
  // turned on ("true") which is the default setting
  test_integration = false
}

variable "channel_name" {
  type    = string
  default = "Service Now Channel Alert Example"
}

variable "instance_url" {
  type    = string
  default = "https://dev123.service-now.com"
}

variable "username" {
  type    = string
  default = "snow-user"
}

variable "password" {
  type    = string
  default = "snow-pass"
}

variable "custom_template_file" {
  type    = string
  default = <<TEMPLATE
  {
    "description" : "Generated by Lacework:",
    "approval" : "Approved"
  }
  TEMPLATE
}

output "channel_name" {
  value = lacework_alert_channel_service_now.example.name
}

output "instance_url" {
  value = lacework_alert_channel_service_now.example.instance_url
}

output "username" {
  value = lacework_alert_channel_service_now.example.username
}

output "custom_template_file" {
  value = lacework_alert_channel_service_now.example.custom_template_file
}