// Code generated by: scripts/version_updater.sh
// File generated at: 20220808162644
//
// <<< DO NOT EDIT >>>
//

package lacework

// version is the semver coming from the VERSION file
const version = "0.23.0"
