// Code generated by: scripts/version_updater.sh
// File generated at: 20220519133940
//
// <<< DO NOT EDIT >>>
//

package lacework

// version is the semver coming from the VERSION file
const version = "0.19.1-dev"
