// Code generated by: scripts/version_updater.sh
// File generated at: 20210428131607
//
// <<< DO NOT EDIT >>>
//

package lacework

// version is the semver coming from the VERSION file
const version = "0.3.2"
